name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Heroku CLI
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh

    - name: Log in to Heroku
      run: heroku login -i
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}  # Add your secret name for Heroku API key

    - name: Deploy to Heroku
      run: |
        heroku create
        heroku container:push web -a udacity-salary-predictor
        heroku container:release web -a udacity-salary-predictor
